tasks:
  - before: |
      sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      npm install
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get install -q -y libunwind-dev
      dfx start --background
   

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Dev Server
    port: 3000
    visibility: public
    onOpen: open-browser